define({
    "About":"关于",
    "Add":"添加",
    "Add to Launcher":"添加到主页",
    "Add success":"已经添加成功！",
    "Add this webpage to Home for quick access.":"将此网页添加到主页以便快速访问",
    "Too many tabs opened. Close existing ones before opening the new one.":"打开的网页过多。请在开打新的网页前关闭现有网页",
    "Add to Bookmarks":"添加至书签",
    "Add to Speed Dial":"添加至我的导航",
    "Add Link to Speed Dial":"将链接添加至我的导航",
    "Add Link to Bookmarks":"将链接添加至书签",
    "Add Page to Speed Dial":"将页面添加至我的导航",
    "Add Page to Bookmarks":"将页面添加至书签",
    "Add to Speed Dial":"添加至我的导航",
    "Add to Bookmarks":"添加至书签",
    "All":"所有",
    "Back":"后退",
    "Bookmark Error":"书签错误",
    "Bookmark deleted":"书签已删除",
    "Bookmark is already on the list!":"书签已在列表中！",
    "Bookmark moved":"书签已移动",
    "Bookmark not found in device memory":"在设备内存中未找到书签",
    "Bookmark saved":"书签已保存",
    "Bookmarks":"书签",
    "Cancel":"取消",
    "Certificate":"证书",
    "Change Zoom in Menu > Settings":"在菜单 > 设置中更改缩放",
    "Clear History":"清除历史记录",
    "Clear All Cookies":"清除所有 Cookie",
    "Clear All Bookmark":"删除所有书签",
    "Close":"关闭",
    "Close Current Tab":"关闭当前标签",
    "Close Tab":"关闭标签",
    "Close Tabs":"关闭标签",
    "Connection":"连接",
    "Cookies Disabled":"Cookie 已禁用",
    "Cookies Enabled":"Cookie 已启用",
    "Could not delete Speed Dial entry":"无法删除我的导航条目",
    "Could not delete bookmark from memory":"无法从内存删除书签",
    "Could not load Speed Dial entries":"无法载入我的导航条目",
    "Could not load bookmarks file!":"无法载入书签文件！",
    "Could not load history from memory":"无法从内存载入历史记录",
    "Could not modify Speed Dial entry":"无法修改我的导航条目",
    "Could not modify bookmark in memory":"无法修改内存中的书签",
    "Could not move Speed Dial entry":"无法移动我的导航条目",
    "Could not save Speed Dial entry":"无法保存我的导航条目",
    "Could not save bookmark in memory":"无法将书签保存至内存中",
    "Delete":"删除",
    "Delete Speed Dial Entry?":"删除我的导航条目？",
    "Delete Bookmark?":"删除书签？",
    "Disable Ads":"屏蔽广告",
    "Disable All Page Ads":"屏蔽所有广告",
    "Disable Webpage":"屏蔽网站",
    "Do you want to clear history?":"是否要清除历史记录？",
    "Close Opera TV Browser?":"关闭 Opera TV Browser？",
    "Do you want to close the tab \"$title\"?":"是否要关闭标签 \"$title\"？",
    "Done":"完成",
    "Edit":"编辑",
    "Edit Bookmarks":"编辑书签",
    "Edit Speed Dial":"编辑我的导航",
    "Edit bookmark":"编辑书签",
    "Edit mode":"编辑模式",
    "Exit":"退出",
    "Exit the Browser":"退出浏览器",
    "Do you want to exit the Browser?":"是否退出浏览器？",
    "First Visited":"首次访问",
    "Forward":"前进",
    "Help":"帮助",
    "History":"历史记录",
    "History cleared":"历史记录已清除",
    "JavaScript Disabled":"JavaScript 已禁用",
    "JavaScript Enabled":"JavaScript 已启用",
    "Last Month":"上月",
    "Log In":"登录",
    "Menu":"菜单",
    "Move":"移动",
    "Move Speed Dial entry":"移动我的导航条目",
    "Move down to hide address bar":"下移以隐藏地址栏",
    "New Tab":"新建标签",
    "No Name":"无标题",
    "OK":"确认",
    "Open Link in New Tab":"在新标签中打开链接",
    "Opera Help":"Opera 帮助",
    "Page Security":"页面安全",
    "Password":"密码",
    "Forget your password" : "忘记了你的密码?",
    "Please fill in both name and address fields":"请填写名称和地址字段",
    "Privacy":"隐私",
    "Move <b>Up</b> to access the address bar":"<b>向上</b>移动，以访问地址栏",
    "Reload":"重新载入",
    "SeamlessBrowsingMode":"无痕浏览模式",
    "Restore Default Settings":"还原默认设置",
    "Secure Connection":"安全连接",
    "Security Information":"安全信息",
    "Select a Speed Dial entry to edit":"选择要编辑的我的导航条目",
    "Select a bookmark to edit":"选择要编辑的书签",
    "Select a new location for the bookmark":"为书签选择新位置",
    "Select a tab to close":"选择要关闭的标签",
    "Select action":"选择操作",
    "Settings":"设置",
    "Show All History":"显示所有历史记录",
    "Sign in" : "登录",
    "Sign up" : "注册",
    "Sign in with Google" : "使用Google账号登录",
    "Use your phone or Laptop" : "使用phone或者Laptop账号登录",
    "Enter Username or Email":"输入用户名称或者邮箱",
    "Username or Email" : "用户名称或者邮箱",
    "Speed Dial":"我的导航",
    "Speed Dial Error":"我的导航错误",
    "Speed Dial entry modified":"我的导航条目已修改",
    "Speed Dial entry moved":"我的导航条目已移动",
    "Speed Dial entry deleted":"我的导航条目已删除",
    "Speed Dial with given address already exists":"指定地址的我的导航已存在",
    "Stop":"停止",
    "Tabs":"标签",
    "There was a problem while clearing history":"清除历史记录时出现问题",
    "This connection certificate is untrusted!":"此连接证书不可信！",
    "This connection is NOT secure.":"此链接不安全。",
    "This connection is secure.":"此连接安全。",
    "Unsecured Connection":"不安全的链接",
    "Untrusted Connection":"不可信的链接",
    "Username":"用户名",
    "Webpage address is too long. Please reduce the length of the address.":"地址太长。请缩短该地址的长度。",
    "You cannot open additional tabs":"无法打开更多标签",
    "You browse this website often. Would you like to bookmark it?":"您多次浏览此网站，是否加其加入收藏？",
    "Zoom":"缩放",
    "address":"地址",
    "name":"名称",
    "Bookmark not saved: the address is too long":"书签未保存：地址太长",
    "Bookmark not saved: you have reached the maximum number":"书签未保存：已达到数量上限",
    "Speed Dial entry not saved: you have reached the maximum number":"我的导航条目未保存：已达到数量上限",
    "Speed Dial entry not saved: the address is too long":"我的导航条目未保存：地址太长",
    "Search or enter address":"搜索或输入网址",
    "Close Tab":"关闭标签",
    "Exit Opera TV Browser":"退出 Opera TV Browser",
    "Speed Dial entry saved":"我的导航条目已保存",
    "Management":"管理",
    "Clear All Browsing Data":"清除所有数据",
    "Clear":"清除",
    "Clear history":"清除历史",
    "Clear All Cookies":"清除所有Cookies",
    "Today":"今天",
    "Yesterday":"昨天",
    "Last Week":"上周",
    "Before":"以前",
    "Monday":"星期一",
    "Tuesday":"星期二",
    "Wednesday":"星期三",
    "Thursday":"星期四",
    "Friday":"星期五",
    "Saturday":"星期六",
    "Sunday":"星期日",
    "January":"一月",
    "February":"二月",
    "March":"三月",
    "April":"四月",
    "May":"五月",
    "June":"六月",
    "July":"七月",
    "August":"八月",
    "September":"九月",
    "October":"十月",
    "November":"十一月",
    "December":"十二月",
    "loading...":"正在载入...",
    "Page Turn":"翻页",
    "Previous":"返回",
    "Next":"前进",
    "Add Bookmark":"增加书签",
    "Home":"首页",
    "Management": "书签管理",
    "Yesterday": "昨天",
    "Last Week": "上周",
    "Before": "往前",
    "Clear All": "清除",
    "Clear Cookies": "清除Cookies",
    "Clear": "清除",
    "Recommended": "推荐",
    "Interested in the following website which you browser often?": "这是你经常浏览的网站。愿意收藏它吗？",
    "Bookmark added": "书签添加成功",
    "Website already added": "该网站已添加",
    "Add failed": "添加失败",
    "Homepage": "主页",
    "The input address may be incorrect; check if the address is correct":"可能输入的地址错误，检查是否正确。",
    "Privacy":"隐私",
    "Account":"账号",
    "Security":"安全"
})
